### ISSUE TITLE
Question about implementing configuration

### ISSUE THREAD

**Issue by orblua** [steven2024/xfce-winxp-tc-installer#1]
I'm curious to know how you plan on automating the configuration of xfce after the install process, as this is something im trying to do myself. Great work so far!

**Comment by steven2024** [comment]
Thank you! Automating the configuration of XFCE after the install process involves a few steps. Here’s how I would do it: using shell scripts to install required packages and configuration files, utilizing xfconf-query to set various XFCE settings programmatically, and creating and copying pre-configured configuration files to the appropriate directories. This approach should streamline the setup process significantly.

**_Note_**: _Rozniak has begun the process of porting my theme installer work to C for integration with his theme. This work is still in progress, and the C-based version is not yet complete. His goal is to enhance the theme installer to be more closely integrated with the theme itself. I'm not planning to work on it anymore because Rozniak has started working on his implementation._

**Comment by orblua** [comment]
That clears things up for me, thanks! Looking forward to seeing this work in Rozniak's theme.

**Comment by Lauel09** [comment]
> **_Note_**: _Rozniak has begun the process of porting my theme installer work to C for integration with his theme. This work is still in progress, and the C-based version is not yet complete. His goal is to enhance the theme installer to be more closely integrated with the theme itself. I'm not planning to work on it anymore because Rozniak has started working on his implementation._

Sorry to intrude. I cloned it and was working on this, to see how it goes. Cleaned path issues, added logging, and later I was wondering is the installer broken? Clicking the next button does nothing. 
Also can you share the C implementation of the same installer?
Thank you for a fine installer. I did use PyGobject sometimes ago, twas messy.

**Comment by steven2024** [comment]
The C-implementation is very early along  and I haven't talked to him recently so I don't know of any progress or if hes worked on it any. He's done some work on the graphical mode UI as seen below and I don't have the C implementation since it isn't even close to finished or even in a working state (keep in mind i haven't talked to him in a while so I don't know if he's done anything.) Also I don't have the current version since it's not my project and I've never even written anything in C.

>working on the UI for graphical mode 
> yeah i will have a look at the OOBE as well
i'm sort of trying to get the phases prepared, and then work on linking them up and getting the install working
not a 2 second job mind you but it will get done
![image](https://github.com/user-attachments/assets/530a5270-0cec-4f18-a95d-b12b223e3b7c)
>booted from systemd in arch
![image](https://github.com/user-attachments/assets/470ffa0a-a258-4da4-aad3-aca44d48c6c4)

By the way, it doesn't have the code for downloading the repo and installing the internals because I never pushed all my changes to git, so this is out of date. I can try and push it and maybe look at fixing some stuff.

I have also have a list of stuff I need to get done for the project (as seen in the screenshot below)
![image](https://github.com/user-attachments/assets/49427721-c874-4451-8439-88b84720f200)

**Comment by Lauel09** [comment]
> The C-implementation is very early along and I haven't talked to him recently so I don't know of any progress or if hes worked on it any. He's done some work on the graphical mode UI as seen below and I don't have the C implementation since it isn't even close to finished or even in a working state (keep in mind i haven't talked to him in a while so I don't know if he's done anything.) Also I don't have the current version since it's not my project and I've never even written anything in C.
> 
> > working on the UI for graphical mode
> > yeah i will have a look at the OOBE as well
> > i'm sort of trying to get the phases prepared, and then work on linking them up and getting the install working
> > not a 2 second job mind you but it will get done
> > ![image](https://private-user-images.githubusercontent.com/89735533/355348724-530a5270-0cec-4f18-a95d-b12b223e3b7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Mjk3NzcsIm5iZiI6MTcyMjkyOTQ3NywicGF0aCI6Ii84OTczNTUzMy8zNTUzNDg3MjQtNTMwYTUyNzAtMGNlYy00ZjE4LWE5NWQtYjEyYjIyM2UzYjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA3MzExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZWQ5ZGJjNWE5MTUzMDA4NTQxZmQzNGJkMDVjMWFkZTkyNjNkOTViMWMxZWEyMjc4ZmIxYmViMGRhNTlhZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._5YUsJo_93x70YEsPPsiXG3a0YQm0wr-n6WNRYsp44I)
> > booted from systemd in arch
> > ![image](https://private-user-images.githubusercontent.com/89735533/355348772-470ffa0a-a258-4da4-aad3-aca44d48c6c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Mjk3NzcsIm5iZiI6MTcyMjkyOTQ3NywicGF0aCI6Ii84OTczNTUzMy8zNTUzNDg3NzItNDcwZmZhMGEtYTI1OC00ZGE0LWFhZDMtYWNhNDRkNDhjNmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA3MzExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0OGI4MWEzZjI2NjE3MzhlMzlmZjRlMWFhMDgwNTFjOTMxMzBmYWEyZTRiNzI1YjIxZDU3NjQ4MDZlMThjMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TMTP0R8ZxMrKaiw7pjmzJmchjTe6jvZ2q_VXpYd8CaU)
> 
> By the way, it doesn't have the code for downloading the repo and installing the internals because I never pushed all my changes to git, so this is out of date. I can try and push it and maybe look at fixing some stuff.
> 
> I have also have a list of stuff I need to get done for the project (as seen in the screenshot below) ![image](https://private-user-images.githubusercontent.com/89735533/355350990-49427721-c874-4451-8439-88b84720f200.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Mjk3NzcsIm5iZiI6MTcyMjkyOTQ3NywicGF0aCI6Ii84OTczNTUzMy8zNTUzNTA5OTAtNDk0Mjc3MjEtYzg3NC00NDUxLTg0MzktODhiODQ3MjBmMjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA3MzExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MmM0OGFjZjBmY2FhZGNlOGU3YzdkNGEzYTI3MDU5OTFmY2U2OTZkYTg5MmNjNmNkMGVkODA3Yjc1YThiNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BVeMIwldHlBfoERMTflEd1ll5Rk_Hj8y81EEzwZVvMk)

If possible, may I ask, if you can push it somewhere ?(a new repo if not this). I was thinking to play with it, just code no fixes might be good.
Thanks for the quick reply.

**Comment by steven2024** [comment]
I can push it here since the current version in this repo is broken and if you need any info, just ask me :)

**Comment by Lauel09** [comment]
> I can push it here since the current version in this repo is broken and if you need any info, just ask me :)

Thank you, sir. That would be great. (^‿^)

**Comment by steven2024** [comment]
> > I can push it here since the current version in this repo is broken and if you need any info, just ask me :)
> 
> Thank you, sir. That would be great. (^‿^)

It's pushed to this repo now :D

**Comment by steven2024** [comment]
![355350990-49427721-c874-4451-8439-88b84720f200](https://github.com/user-attachments/assets/f0852847-6bff-497d-9508-d6fd128e26b5)
Regarding the issue mentioned in the screenshot above: If you're up to it, I'd really appreciate it if you could look into the text positioning issues when going to the next installer "screen." I've spent hours trying to fix it but haven't been able to figure it out.

**Comment by Lauel09** [comment]
Thanks for the reply and the push. I will look into it. :smiley:

**Comment by steven2024** [comment]
> > **_Note_**: _Rozniak has begun the process of porting my theme installer work to C for integration with his theme. This work is still in progress, and the C-based version is not yet complete. His goal is to enhance the theme installer to be more closely integrated with the theme itself. I'm not planning to work on it anymore because Rozniak has started working on his implementation._
> 
> 
> 
> Sorry to intrude. I cloned it and was working on this, to see how it goes. Cleaned path issues, added logging, and later I was wondering is the installer broken? Clicking the next button does nothing. 
> 
> Also can you share the C implementation of the same installer?
> 
> Thank you for a fine installer. I did use PyGobject sometimes ago, twas messy.
> 
> Edit: I can't help but ask that there is no code which actually downloads the repo, and installs the internals or has it been deleted with the C implementation announced?

> Per title - port across the work done by @steven2024 on #320 for the OOBE into C under /base/setup/oobe

So it's under /base/setup/oobe in [xfce-winxp-tc](https://github.com/rozniak/xfce-winxp-tc)
